services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: raizes-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - WorkerUrl=http://worker:5200
    depends_on:
      - worker
    networks:
      - raizes-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: payment-worker
    ports:
      - "5200:5200"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5200
    networks:
      - raizes-network

networks:
  raizes-network:
    driver: bridge
